# Generated by Django 6.0.2 on 2026-03-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_planned_pieces', models.IntegerField()),
                ('total_actual_pieces', models.IntegerField()),
                ('total_downtime_minutes', models.IntegerField()),
                ('total_defects', models.IntegerField()),
                ('availability', models.FloatField()),
                ('performance', models.FloatField()),
                ('quality', models.FloatField()),
                ('oee_percentage', models.FloatField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cell')),
            ],
            options={
                'verbose_name_plural': 'Recaps',
            },
        ),
    ]
