# Generated by Django 5.2.5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_remove_plannedproduction_unique_workorder_per_date'),
        ('core', '0001_initial'),
    ]

    operations = [
        # This is a placeholder migration
        # The actual model changes were handled by migrations 0012-0014
    ]
