# Generated by Django 5.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_rename_model_routing_to_model'),
        ('core', '0001_initial'),
    ]

    operations = [
        # Add a new temporary field that points to the correct Model table
        migrations.AddField(
            model_name='productiondetail',
            name='model_temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.model'),
        ),
    ]

