# Generated by Django 5.2.5

from django.db import migrations


def copy_model_data(apps, schema_editor):
    """
    Copy the model_id from modelRouting to the new model_temp field.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Get all productionDetail records
        cursor.execute("SELECT id, model_id FROM planning_productiondetail")
        records = cursor.fetchall()
        
        # For each record, get the actual model_id from the modelRouting table
        for record_id, model_routing_id in records:
            if model_routing_id:
                cursor.execute("SELECT model_id FROM core_modelrouting WHERE id = %s", [model_routing_id])
                result = cursor.fetchone()
                if result:
                    actual_model_id = result[0]
                    cursor.execute(
                        "UPDATE planning_productiondetail SET model_temp_id = %s WHERE id = %s",
                        [actual_model_id, record_id]
                    )


def reverse_copy_model_data(apps, schema_editor):
    """
    Reverse operation - not needed but included for completeness
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_add_temp_model_fk'),
    ]

    operations = [
        migrations.RunPython(copy_model_data, reverse_copy_model_data),
    ]

