# Generated by Django 5.2.5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_copy_model_data'),
    ]

    operations = [
        # Remove the old field
        migrations.RemoveField(
            model_name='productiondetail',
            name='model',
        ),
        # Rename the temporary field to the final name
        migrations.RenameField(
            model_name='productiondetail',
            old_name='model_temp',
            new_name='model',
        ),
    ]

